# -*- coding: utf-8 -*-
"""make_food_one_hot_tokendata

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SAOElWKwzUvl-vBc3I3xUkV7gBBPX1-j
"""

import json
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

wine_meta = '/content/drive/MyDrive/tobigs14_conference/data/v_2/oldfile/Wine_Meta_v1_201129.json'
wine_meta = pd.read_json(wine_meta)

food=wine_meta.iloc[:, [1, 11]]

food

# 특수문자 제거
food['food']=food['food'].map(lambda x: str(x).lstrip('[').rstrip(']'))
food['food'].replace(r'\([^)]*\)', '', regex=True, inplace=True)
food['food'].replace(r',', '|', regex=True, inplace=True)

# 원핫 인코딩
one_hot=pd.Series(food['food']).str.get_dummies()

food['food']=food['food'].map(lambda x: str(x).lstrip('[').rstrip(']'))

food_one_hot=pd.merge(food, one_hot, left_index=True, right_index=True, how='left')

import re
document = re.sub(r'[^ ㄱ-ㅣ가-힣A-Za-z]', '', str(list(food_one_hot.columns))) #특수기호 제거, 정규 표현식

col_list=[]
for i in food_one_hot.columns:
    col_list.append(i.lstrip().rstrip().strip("'"))

food_one_hot.columns=col_list

food_one_hot=food_one_hot.sort_values('wine_id')

food_one_hot.reset_index(drop=True, inplace=True)

food_one_hot.head()

food_one_hot.to_csv('food_token_one_hot.csv')
files.download('food_token_one_hot.csv')

food_token_one_hot = '/content/drive/MyDrive/tobigs14_conference/data/v_2/food_token_one_hot.csv'
food_token_one_hot_wine = pd.read_csv(food_token_one_hot)